name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'An example input for the manual workflow'
        type: string
        default: 'Default value'
      number-required:
        description: 'A required input for the manual workflow'
        type: number
        required: true
jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Step
        run: echo "${ { github.event.inputs.name } }"