name: Manual Workflow
on:
  workflow_dispatch:

    inputs:
      name:
        description: 'An example input for the manual workflow'
        type: string
        default: 'Default value'
      age:
        description: 'Age required for the manual workflow'
        type: number
        required: true
      gender-choice:
        description: 'A dropdown input for the manual workflow'
        type: choice
        options:
          - Male
          - Female
          - Other
        default: 'Male'
      married-choice:
        description: 'Is the person married?'
        type: boolean
        default: false
 
       

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Step
        run: echo "${{ github.event.inputs.name }}"

      - name: Age Step
        run: echo "${{ github.event.inputs.age }}"
    
      - name: Gender 
        run: echo "${{ github.event.inputs.gender-choice }}"
    
      - name: Married
        run: echo "${{ github.event.inputs.married-choice }}"

    
